### PR TITLE
Add transaction examples

### PR DESCRIPTION
**Pull request by jasonniebauer**
Please see the full transaction and decline I have added to the transaction example.

### CODE REVIEW

**Comment by maanas** [comment]
Merged, Changing the library loading path

**Comment by maanas** [comment]
Merged and also correct library load path.
We should actually load the library from ruby gems

**Comment by jasonniebauer** [comment]
Would the gem load the full Ruby library or only a certain part of it?

**Comment by maanas** [comment]
Full library from ruby gems
give a try, it is available in the global path as well

**Pull request merged**
